### ISSUE TITLE
'dateFormat' => 'php:U'

### ISSUE THREAD

**Issue by fiSCIENCES** [yiisoft/yii2-jui#110]
Hello,

'dateFormat' => 'php:U' return millisecond instead of second as mention for time() function.

`<?= $form->field($model, 'birthdate')->widget(DatePicker::class, [
    'language' => Yii::$app->language, // It's currently fr-CA or en-CA
    'dateFormat' => 'php:U', // Yii::t('SLc', 'str_date_format'),   // WAS: 'yyyy-MM-dd'
    'inline' => false,
    'options' => ['placeholder' => Yii::t('SLc', 'str_date_format')],
]) ?>`
'birthdate' is a integer in SQL.

Quick solution/work around until fix?

Thank you.

**Comment by bizley** [comment]
The date format for JUI is converted to one of [JUI's values](https://api.jqueryui.com/datepicker/#utility-formatDate) so it is not a PHP format. I'm afraid there is no option there to get only seconds in Unix time. You need to convert it yourself after receiving it from the widget.

**Comment by fiSCIENCES** [comment]
OK, could you guide me on the best/simple method to use to do that?
So I would need to do time() * 1000 before setting the value in DatePicker and / 1000 after DatePicker is run.
Widget::afterRun and beforeRun?
Thank you Bizley, you seem to be everywhere in Yii2!

**Comment by bizley** [comment]
It was a long time since I use this so I'm not sure how many places needs to be changed. If this is a problem only with saving the value for a model maybe you could only normalize the model's property. If this widget is used in many places some global modifications are indeed required. Anyway, hard to say.
