### ISSUE TITLE
The github links in the documentation give a 404

### ISSUE THREAD

**Issue by kanyuga** [yiisoft/yii2-jui#17]
The links for the attributes, methods and classes are not pointed correctly.

**Comment by cebe** [comment]
can you give an example? Which links are you talking about?

**Comment by kanyuga** [comment]
E.g. the [yii\jui\AutoComplete](http://www.yiiframework.com/doc-2.0/yii-jui-autocomplete.html) source code link is
> https://github.com/yiisoft/yii2/blob/master/extensions/jui/AutoComplete.php

the [yii\jui\AutoComplete::run()](http://www.yiiframework.com/doc-2.0/yii-jui-autocomplete.html#run%28%29-detail) view source on Github link is 
> https://github.com/yiisoft/yii2/blob/master/extensions/jui/AutoComplete.php#L58

**Comment by cebe** [comment]
Fixed, thanks for reporting! Website will take some time to update.
