### ISSUE TITLE
Does not work with bower-asset directory

### ISSUE THREAD

**Issue by SteveSimpson** [yiisoft/yii2-jui#24]
I have 2 installs with jquery-ui. My development box has vendor/bower/jquery-ui - it works fine. 

My test box has vendor/bower-asset/jquery-ui and this does not work, I get:
```
Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: _________/app/vendor/bower/jquery-ui
```

I have completely reinstalled vendor directories with "composer install" and the exact same composer.json & composer.lock files on both systems & they still reinstall to bower and bower-asset, respectively, I'm not a composer expert and don't really want to spend the time to figure out why they are different.

But this should work no matter where it is installed, all the standard jquery stuff does.

The work around is simple:
```
cd vendor
ln -s bower-asset bower
```

**Comment by samdark** [comment]
Make sure you have the following line in your composer.json: https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L49

**Comment by SteveSimpson** [comment]
Thanks, but the line is there...

Same composer.json, composer.lock and version of composer.

```
$ cat composer.json 
{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Application Template",
    "keywords": ["yii2", "framework", "basic", "application template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiisoft/yii2-jui": "2.0.4",
        "ssimpson/yii2-opensslca": "dev-master",
        "phpseclib/phpseclib": "^0.3.10"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
```

**Comment by samdark** [comment]
Do you have fxp composer plugin installed globally?

**Comment by SteveSimpson** [comment]
yes - I have that on my dev box, but not on the test (problem) system

**Comment by samdark** [comment]
Well, that's the reason.

**Comment by SteveSimpson** [comment]
Is fxp composer a requirement for jquery-jui? What in the world are you talking about?

The system that is broken does not have fxp composer at all...

**Comment by SteveSimpson** [comment]
OK - to answer my own questions (if anyone else happens to have the same problem):
Yes fxp composer is a requirement (I'm still not sure why it isn't listed as a dependency). It is referenced in the Yii2 installation if you install via composer (which I did not).

Backstory here is that bower is node.js package manager and composer needs fxp/composer-asset-plugin to interface correctly with those packages.

Please let me know if I got any of this wrong. And thanks to samdark for replying quickly to this issue.

Here are the references that we found while trying to figure this out:
- http://stackoverflow.com/questions/25882271/cannot-update-yii2-via-composer-bower-asset-jquery-could-not-be-found
- http://www.yiiframework.com/doc-2.0/guide-start-installation.html
- https://github.com/francoispluchino/composer-asset-plugin

**Comment by B0rner** [comment]
> Yes fxp composer is a requirement

Is this still valid? And: is fxp still needed? I installed current Yii2 version using composer without adding the fxp asset plugin an it works.

**Comment by samdark** [comment]
It's not. fxp isn't require for application templates nowadays.
