### ISSUE TITLE
Can not attach an event to SliderInput create

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2-jui#30]
`SliderInput` provides a `create` clientside event. But currently it's not possible to attach a handler there, because the inline code that attaches the event handler comes after the init code for the slider itself - which is too late:

```
    <?= $form->field($model, 'minPrice')
        ->widget(SliderInput::className(), [
            'clientOptions' => [
                'min' => 0,
                'max' => $priceLimit,
            ],
            'clientEvents' => [
                'create' => $sliderHandler,
            ],
        ]);
    ?>
```

Leads to this inline js code:

```
jQuery('#minPrice-container').slider({...});
jQuery('#minPrice-container').on('slidecreate',   function(event, ui) { ... });
```

So the `clientEvents` should be attached first, then the widget should be initialized.

**Comment by jayhewitt** [comment]
Pull Request #33 resolves this issue by applying events first
