### ISSUE TITLE
How to add "onClose" event to datepicker?

### ISSUE THREAD

**Issue by abrgitlab** [yiisoft/yii2-jui#35]
I want to bind two datepickers for choosing period. So, date of the first one should be lower than second one. I want to use datepicker's "onClose" option. But I can't find something looks like this in the manual of widget.
What the best way to add option "onClose" or maybe you know another method for choosing period with JQuery UI components?

**Comment by samdark** [comment]
Please use forum for questions. GitHub is for bugs and feature requests. Thanks!
