### ISSUE TITLE
Wrong event names in Draggable

### ISSUE THREAD

**Issue by antonmarin** [yiisoft/yii2-jui#36]
Currently uses draggable{event_name} for event names. And documentation says different http://api.jqueryui.com/draggable/#events

Solution: add 
```
	protected $clientEventMap = [
		'create' => 'dragcreate',
		'drag' => 'drag',
		'stop' => 'dragstop',
		'start' => 'dragstart',
	];
```

**Comment by samdark** [comment]
Merged. Thanks!
