### ISSUE TITLE
Droppable and draggable events not working

### ISSUE THREAD

**Issue by jeesus** [yiisoft/yii2-jui#41]
### What steps will reproduce the problem?
Attached `clientEvents` to Droppable widget like this:
`            "clientEvents" => [
                "drop" => "function (event, ui) {
                    alert(ui);
                    }"
            ]`
### What's expected?
Expected an alert when the item is dropped at the area.
### What do you get instead?
No alert popped.

### Additional info
jQuery added inline at the end of the page uses another set of event names:
`Query('#omitted_services').on('droppabledrop', function (event, ui) {
                    alert(ui);
                    });`

Same thing happens with Draggable events.
| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0.9
| PHP version      |  7.0.7
| Operating system |  Ubuntu

**Comment by samdark** [comment]
Try code from master: https://github.com/yiisoft/yii2-jui/blob/master/CHANGELOG.md#206-under-development

**Comment by jeesus** [comment]
Works for Draggable but not for Droppable, which hasn't been updated for a long time.

**Comment by samdark** [comment]
Fixed. Thanks for reporting.
