### ISSUE TITLE
`DatePicker` conflict.

### ISSUE THREAD

**Issue by wao138** [yiisoft/yii2-jui#44]
When I use `DatePicker` on page, like as 

```php
<?= DatePicker::widget([
                    'model' => $context->model,
                    'attribute' => 'date',
                    'options' => [
                        'required' => 'true',
                        'placeholder' => 'Select date',
                        'class' => 'form-control',
                    ],
                ]); ?>
```

In popup I get conflict, when use `DatePicker` in form:
```php
<?= $form->field($model, 'date')->widget(DatePicker::className(), [
            'clientOptions' => [
                'class' => 'form-control',
            ],
        ]) ?>`
```

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 5.4.45
| Operating system | Linux

**Comment by cebe** [comment]
what kind of conflict, what is the issue exactly?

**Comment by wao138** [comment]
@cebe , the widget is not initialized.

**Comment by samdark** [comment]
Any messages in console?

**Comment by cebe** [comment]
@wao138 is `$context->model` in the first widget of the same type as `$model` in the second one? if so, the elements might have the same id and that causes the conflict.

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
