### ISSUE TITLE
How to prevent selection of date after today?

### ISSUE THREAD

**Issue by ianpierreg** [yiisoft/yii2-jui#49]
That's what I have tried:

 <div class="col-md-2"><?= $form->field($pessoa_has_infracao, 'data')->widget(DatePicker::classname(),[
                    'name' => 'to_date',
                    'clientOptions' => [
                        'dateFormat' => 'dd/MM/yyyy',
                        'maxDate' => '0',
                    ],
                    'options' => [
                        'maxDate' => '0',
                        'class' => 'round form-control',
                        'placeholder' => "Data"
                    ],
                ])->label(false);
                ?></div>

Note that I put maxDate inside both clientOptions and options because I don't know where I should place it. Anyways, it didn't work.

How can I do it?

**Comment by samdark** [comment]
Try `0` as number instead of string.

**Comment by eramudeep** [comment]
> Try `0` as number instead of string.

Not working either :(
