### ISSUE TITLE
DatePicker problem with php7.0-intl

### ISSUE THREAD

**Issue by fadiabualnaser** [yiisoft/yii2-jui#59]
### What steps will reproduce the problem?
I works on multi language application arabic and english
the problem that when i want to edit a date while i am open the backend as arabic language the date shows as arabic numbers and if i save the form the data will saved as arabic numbers to my database.
Edit date form :
```php
<?= $form->field($model, 'match_date')->widget(\yii\jui\DatePicker::classname(),[
      'language' => Yii::$app->language,
      'dateFormat' => 'yyyy-MM-dd',
      'options' => ['class' => 'form-control']
]) ?>
```
<img width="354" alt="screen shot 2017-03-28 at 8 02 20 pm" src="https://cloud.githubusercontent.com/assets/5568413/24420065/c36aedd2-13f1-11e7-8601-7eb11bda2728.png">

On my frontend application i install php intl and yii2 formatter works good for me but the arabic date will show an error and the page failed to load because the arabic numbers
<img width="1365" alt="screen shot 2017-03-28 at 8 02 33 pm" src="https://cloud.githubusercontent.com/assets/5568413/24420180/439dd26c-13f2-11e7-986c-8fc8d5d21012.png">

I think DatePicker must always saved date as english 

| Yii vesion       | 2.0.6
| PHP version      | 7
| Operating system | ubuntu

**Comment by samdark** [comment]
It's consistent with JQueryUI behavior. You have to do something like https://jqueryui.com/datepicker/#alt-field in order to achieve what you need.

Since this extension tends to be a thin wrapper, we aren't going to change default jQueryUI behavior.
