### ISSUE TITLE
JUI uses legacy JQueryUI release?

### ISSUE THREAD

**Issue by Exerionius** [yiisoft/yii2-jui#63]
Composer dependency of JUI require
`"bower-asset/jquery-ui": "1.11.*@stable"`
while current jQueryUI stable version is 1.12.1

I want to use 'classes' option of Widget Factory, but it's available only in 1.12+ versions of  jQueryUI.
Composer can't update JUI to this version now. Do I really have to install this version manually?

**Comment by sosojni** [comment]
I just ran into this problem. If i use any release after 2.0.0-beta, i get jquery errors in autocomplete forms and they are not working. Error in console is: TypeError: elem.getClientRects is not a function[Learn More]
To fix this error one has to use 1.12 version of jquery-ui but yii2-jui is limited to 1.11 version. To fix my broken app i had to do one of two things, revert yii2-jui to 2.0.0-beta OR fork latest code, change dependancy in composer.json to jquery-ui 1.12 
https://github.com/sosojni/yii2-jui/blob/master/composer.json
Should i create pull request?

**Comment by schmunk42** [comment]
@samdark What's about requiring `"bower-asset/jquery-ui": "^1.11"` - looks easier to read and *should* not break, although I haven't tested this in depth.

**Comment by sosojni** [comment]
Yeah i just updated my fork with your suggestion and it's working that way too (at least in my user case which is pretty limiting). I don't know why it is set up the way it is right now so i cant really say what would be good or bad fix.

**Comment by cebe** [comment]
there are a lot of changes in 1.12 release, need to go through them and check whether yii2-jui needs to be adjusted: http://jqueryui.com/upgrade-guide/1.12/

**Comment by schmunk42** [comment]
@sosojni I haven't tried it for assets, but in your project's `composer.json` you should always be able to use an alias like:

    "bower-asset/jquery-ui": "1.12.1 as 1.11.999"

without forking the package.

**Comment by sosojni** [comment]
Orly? Never used it like that. Ill give it a try, it would be much better than forking :)

**Comment by vinpel** [comment]
@schmunk42 i can confirm this solve my problem

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-jui/commit/36468550d72bce9d963149abe85b13ea2f3a8c18
