### ISSUE TITLE
Autocomplete, clientOptions, source with callback

### ISSUE THREAD

**Issue by lgXenos** [yiisoft/yii2-jui#65]
My Code:
`\yii\jui\AutoComplete::widget([
			'id'          => 'player_search_input',
			'clientOptions' => [
				'minLength' => 3,
				'source'    => "function(request, response){console.log('asd');}"
			]
		]);`
Page Source Code:
`jQuery('#player_search_input').autocomplete({"minLength":3,"source":"function(request, response){console.log(\u0027asd\u0027);}"});`

As you can see: console.log(\u0027asd\u0027); - not need))
So. How I'm can disable qoutting there? 

----

SamDark, Как это безобразие выключить то? Я ж хочу сырой код получить, без обработчиков
С дубляжом на русский)

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/yii-web-jsexpression.html
