### ISSUE TITLE
Composer Problem

### ISSUE THREAD

**Issue by rfiedler** [yiisoft/yii2-jui#68]
### What steps will reproduce the problem?

composer diagnose
Checking composer.json: WARNING
require.yiisoft/yii2 : unbound version constraints (>=2.0.4) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
$ composer require --prefer-dist yiisoft/yii2-jui 

### What do you get instead?
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-jui 2.0.6 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.5 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2-jui ^2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by cebe** [comment]
> require.yiisoft/yii2 : unbound version constraints (>=2.0.4) should be avoided

https://github.com/yiisoft/yii2-jui/blob/75e6f78010e9e9a60d7eecc58c8ad5655778535d/composer.json#L21



> yiisoft/yii2-jui 2.0.6 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.

seems you do not have the composer-asset-plugin installed.

**Comment by rfiedler** [comment]
**composer require fxp/composer-asset-plugin**
**Using version ^1.3 for fxp/composer-asset-plugin**
**./composer.json has been updated**

Loading composer repositories with package information
Updating dependencies (including require-dev)
The "https://bower.herokuapp.com/packages/punycode" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
https://bower.herokuapp.com/packages could not be fully loaded, package information was loaded from the local cache and may be out of date
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-jui 2.0.6 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.5 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2-jui ^2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by cebe** [comment]
> 1. OpenSSL Error messages:
> error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
> Failed to enable crypto
> failed to open stream: operation failed

looks like you also have some networking issues there...

**Comment by cebe** [comment]
> composer require fxp/composer-asset-plugin

should be `composer global require "fxp/composer-asset-plugin:^1.3.1"` see http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-from-composer

**Comment by schmunk42** [comment]
Could you check if you have a (maybe outdated) global installation of the asset-plugin? If so, it would be used on the very first run. Installation in project mode is also not supported, see https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#project-scope-installation - I suggest to update the latest version in **global** mode.

As a workaround you might try described the steps here:
https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/faqs.md#composer-throws-an-exception-stating-that-the-version-does-not-exist

Please see also https://github.com/fxpio/composer-asset-plugin/issues/86 - when trying to "downgrade" an asset package, i.e. you've already installed a newer version.
