### ISSUE TITLE
AutoComplete jquery conflict

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2-jui#71]
### What steps will reproduce the problem?
Upgrade yii2 to 2.0.13, jquery updates 2->3

### What do you get instead?
AutoComplete show value list in wrong position

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.13
| PHP version      |7

**Comment by eLFuvo** [comment]
Until this bug is not fixed you can set jquery version manially in composer.json
"bower-asset/jquery": "~2.2.4"

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-jui/commit/36468550d72bce9d963149abe85b13ea2f3a8c18
