### ISSUE TITLE
f.getClientRects is not a function

### ISSUE THREAD

**Issue by sircovsw** [yiisoft/yii2-jui#72]
### What steps will reproduce the problem?
$("#qqq").dialog("open")

### What's expected?
opens a dialog

### What do you get instead?
f.getClientRects is not a function

### Additional info

| Q                | A
| -------------- | ---
| Yii vesion      | 2.0.13
| PHP version  | 7.1
| Operating system | debian 8

**Comment by giovaANTO** [comment]
I confirm the error too, 

This is a bug caused by the incompatibility between jquery ui 1.11.* and Jquery 3.x.x
[3181](https://github.com/jquery/jquery/issues/3181#issuecomment-226964470)

Yii2 should update the jui assets dependencies.

**Comment by baldiri** [comment]
Hi people,

same error as well. Let me ask a stupid question, who is responsable to update jquery to version 3?

thanks in advance!

**Comment by cebe** [comment]
If there is an incompatibility between jQuery and jQuery UI I would expect this to be reflected in version constraints of the jQueryUI bower package...

**Comment by makroxyz** [comment]
Any news about a fix?

**Comment by samdark** [comment]
Not yet.

**Comment by darwinwen** [comment]
This is the solution, need to be updated JQuery UI 1.11.4 to 1.12.1

https://stackoverflow.com/questions/37914869/jquery-ui-error-f-getclientrects-is-not-a-function

**Comment by lubosdz** [comment]
Also reported here:
https://github.com/vanderlee/colorpicker/issues/132

Currently Yii2 (as of 2.0.13) `vendor/bower/jquery-ui/bower.json` loads `1.11.4`, should be 1.12.1+. 
But probably all Yii2 JUI-* components should be tested ... (:-o)

**Comment by nsanden** [comment]
Migrate script does seem to fix the problem for now

**Comment by diegotejadav** [comment]
Same problem here when trying to add a Parent Menu with in the Yii2-admin menu module:
![screen shot 2017-11-20 at 2 18 26 pm](https://user-images.githubusercontent.com/3412546/33036890-cea36474-cdfd-11e7-8401-cbda693d5fda.png)
When I type some parent menú this is the error:
![Uploading Screen Shot 2017-11-20 at 2.12.34 PM.png…]()

**Comment by IvanMakarenko** [comment]
lubosdz, thx

P.S. Faster fix that please.

**Comment by samdark** [comment]
Pushed a commit to master. That should fix it.

**Comment by tegaradam** [comment]
don't how it works but migration script fix the problem

**Comment by DavidAmorocho** [comment]
migration script? what does this means?

> don't how it works but migration script fix the problem

**Comment by samdark** [comment]
@DavidAmorocho no idea. The issue if fixed in latest version.
