### ISSUE TITLE
Datepicker no Working with Pjax.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [yiisoft/yii2-jui#9]
When you first open the gridview works fine, the datepricker open, once the gridview with pjax the datepicker stops no working, the script is not registered properly, any way to fix it.

Image Datepicker Working:

![jui-datepicker-working](https://cloud.githubusercontent.com/assets/4957021/6967771/4d3c7f0c-d92b-11e4-8350-746eb908e5ce.jpg)

Image Datepicker No Working after filtering:

![jui-datepicker-no-working](https://cloud.githubusercontent.com/assets/4957021/6967785/68556222-d92b-11e4-82a4-ca47f003b160.jpg)

**Comment by smichae** [comment]
Same with SliderInput (and most likely every widget in this package).  One possible solution is a change to registerClientOptions in Widget.php.  This has only been through a small amount of testing, just putting it here as a thought starter.
```php
$js = "$(document).on('ready pjax:success', function() { jQuery('#$id').$name($options); });";
$this->getView()->registerJs($js, \yii\web\View::POS_END);
```

**Comment by szewciu** [comment]
@smichae could you give us please full code of registerClientOptions method including your solution?

**Comment by smichae** [comment]
@szewciu Those two lines in the Apr 15 comment is the solution that's worked for me so far with my setup - just a replacement of current lines 78 & 79.

**Comment by tecnologiaterabyte** [comment]
@smichae You can prepare a pr to solve this problem and close the issue,

Thks,

Wilmer.

**Comment by kasoft** [comment]
I have the same Problem with the Autocomplete Widget. I'm not using Pjax but loading the Page (and the Autocomplete Widget) with Ajax. I tried to put the complete Widget in an extra File and include it with renderAjax - but with no success. It only works the first time you load the complete page.

**Comment by klimov-paul** [comment]
Closed, since has PJAX support is dropped.
